version: 1.0.{build}

matrix:
  fast_finish: false # set this flag to immediately finish build once one of the jobs fails.

environment:
  matrix:
    - GENERATOR: "Visual Studio 14 2015 Win64"
      IDENTIFIER: msvc_2015_x64
    - GENERATOR: "Visual Studio 15 2017 Win64"
      IDENTIFIER: msvc_2017_x64
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    - GENERATOR: "Visual Studio 16 2019"
      IDENTIFIER: msvc_2019_x64
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    
clone_folder: c:\dev

install:
  - cd c:\dev
  - mkdir %IDENTIFIER%
  - mkdir %IDENTIFIER%\include
  # Eigen:
  - ps: wget https://github.com/eigenteam/eigen-git-mirror/archive/3.3.7.zip -O eigen3.zip
  - cmd: unzip eigen3.zip > nul
  - cmake -G"%GENERATOR%" -Heigen-git-mirror-3.3.7 -Bbuild_eigen -DCMAKE_INSTALL_PREFIX=c:/dev/%IDENTIFIER% -DBUILD_TESTING=OFF
  - cmake --build build_eigen --config Release --target INSTALL
  # glog
  - ps: wget https://github.com/google/glog/archive/v0.4.0.zip -O glog.zip
  - cmd: unzip glog.zip > nul
  - cmake -G"%GENERATOR%" -Hglog-0.4.0 -Bbuild_glog -DCMAKE_INSTALL_PREFIX=c:/dev/%IDENTIFIER% -DBUILD_SHARED_LIBS=ON -DWITH_GFLAGS=OFF -DCMAKE_DEBUG_POSTFIX=d
  - cmake --build build_glog --config Release --target INSTALL
  - cmake --build build_glog --config Debug --target INSTALL
  # gflags
  - ps: wget https://github.com/gflags/gflags/archive/v2.2.2.zip -O gflags.zip
  - cmd: unzip gflags.zip > nul
  - cmake -G"%GENERATOR%" -Hgflags-2.2.2 -Bbuild_gflag -DCMAKE_INSTALL_PREFIX=c:/dev/%IDENTIFIER% -DCMAKE_DEBUG_POSTFIX=d
  - cmake --build build_gflag --config Release --target INSTALL
  - cmake --build build_gflag --config Debug --target INSTALL
  # SuiteSparse
  - ps: wget https://github.com/jlblancoc/suitesparse-metis-for-windows/archive/v1.5.0.zip -O suitesparse.zip
  - cmd: unzip suitesparse.zip > nul
  - cmake -G"%GENERATOR%" -Hsuitesparse-metis-for-windows-1.5.0 -Bbuild_suitesparse -DSUITESPARSE_INSTALL_PREFIX=c:/dev/%IDENTIFIER% -DCMAKE_INSTALL_PREFIX=c:/dev/%IDENTIFIER% -DBUILD_METIS=OFF -DLAPACK_DIR="lapack_windows/x64/"
  - cmake --build build_suitesparse --config Release --target INSTALL
  - cmake --build build_suitesparse --config Debug --target INSTALL
  - xcopy /y c:\dev\suitesparse-metis-for-windows-1.5.0\lapack_windows\x64\*.* c:\dev\%IDENTIFIER%\bin\

build_script:
  - cd c:\dev
  - 7z a ceres_deps_%IDENTIFIER%.zip %IDENTIFIER%\*

artifacts:
  - path: ceres_deps_%IDENTIFIER%_.zip
    name: ceres_deps_%IDENTIFIER%
    
deploy:
  provider: GitHub
  auth_token:
    secure: +aBeZ3tfUPQLXLZqrv2OzfI6JNfkg05u9krZqLw318EvdEtLiGBXqUO1EyFGWQY5
  artifact: ceres_deps_%IDENTIFIER%
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true

