version: 1.0.{build}

matrix:
  fast_finish: false # set this flag to immediately finish build once one of the jobs fails.

environment:
  matrix:
    - GENERATOR: "Visual Studio 15 2017 Win64"
      PLATFORM: x64
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    
clone_folder: c:\dev\src

install:
  # Cut some noise as described here: http://bit.ly/2gUJxhC
  - del "C:\Program Files (x86)\MSBuild\14.0\Microsoft.Common.targets\ImportAfter\Xamarin.Common.targets"
  # Eigen:
  - git clone https://github.com/eigenteam/eigen-git-mirror.git
  - ps: wget http://bitbucket.org/eigen/eigen/get/3.3.4.zip -O eigen3.zip
  - cmd: unzip eigen3.zip > nul
  - cmd: mv eigen-eigen-5a0156e40feb c:\dev\install%PLATFORM%\eigen

build_script:
  - cd c:\dev
  - mkdir build
  - cd build
#  - cmake -G"%GENERATOR%" -DCMAKE_PREFIX_PATH=c:/dev/install%PLATFORM% ../src
#  - cmake --build . --config Release --target check
