version: 1.0.{build}

matrix:
  fast_finish: false # set this flag to immediately finish build once one of the jobs fails.

environment:
  matrix:
    - GENERATOR: "Visual Studio 15 2017 Win64"
      PLATFORM: x64
      IDENTIFIER: msvc_2017_x64
      APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    
clone_folder: c:\dev

install:
  # Cut some noise as described here: http://bit.ly/2gUJxhC
  - del "C:\Program Files (x86)\MSBuild\14.0\Microsoft.Common.targets\ImportAfter\Xamarin.Common.targets"
  - cd c:\dev
  - mkdir %IDENTIFIER%
  - mkdir %IDENTIFIER%\include
  # Eigen:
  - ps: wget http://bitbucket.org/eigen/eigen/get/3.3.4.zip -O eigen3.zip
  - cmd: unzip eigen3.zip > nul
  - cmd: mv eigen-eigen-5a0156e40feb\Eigen c:\dev\%IDENTIFIER%\include\Eigen
  # glog
  - ps: wget https://github.com/google/glog/archive/v0.3.5.zip -O glog.zip
  - cmd: unzip glog.zip > nul
  - cmake -G"%GENERATOR%" -Hglog-0.3.5 -Bbuild_glog -DCMAKE_INSTALL_PREFIX=c:/dev/%IDENTIFIER% -DBUILD_SHARED_LIBS=ON -DWITH_GFLAGS=OFF
  - cmake --build build_glog --config Release --target INSTALL
  # gflags
  - ps: wget https://github.com/gflags/gflags/archive/v2.2.1.zip -O gflags.zip
  - cmd: unzip gflags.zip > nul
  - cmake -G"%GENERATOR%" -Hgflags-2.2.1 -Bbuild_gflag -DCMAKE_INSTALL_PREFIX=c:/dev/%IDENTIFIER%
  - cmake --build build_gflag --config Release --target INSTALL
  # SuiteSparse
  - ps: wget https://github.com/jlblancoc/suitesparse-metis-for-windows/archive/v1.3.1.zip -O suitesparse.zip
  - cmd: unzip suitesparse.zip > nul
  - cmake -G"%GENERATOR%" -Hsuitesparse-metis-for-windows-1.3.1 -Bbuild_suitesparse -DCMAKE_INSTALL_PREFIX=c:/dev/%IDENTIFIER% -DBUILD_METIS=OFF
  - cmake --build build_suitesparse --config Release --target INSTALL

build_script:
  - cd c:\dev
  - 7z a ceres_deps_%IDENTIFIER%.zip %IDENTIFIER%\*

artifacts:
  - path: ceres_deps_%IDENTIFIER%.zip
    name: ceres_deps_%IDENTIFIER%

